# Generated by Django 5.2 on 2026-09-15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0002_localaccountstate_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('installment_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(120)])),
                ('purchase_date', models.DateField()),
                ('first_month', models.DateField()),
                ('request_id', models.CharField(max_length=64)),
                ('cancelled_from_month', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.card')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='finance.installmentpurchase'),
        ),
        migrations.AddConstraint(model_name='installmentpurchase', constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='installment_purchase_positive')),
        migrations.AddConstraint(model_name='installmentpurchase', constraint=models.CheckConstraint(condition=models.Q(('installment_count__gte', 2), ('installment_count__lte', 120)), name='installment_count_range')),
        migrations.AddConstraint(model_name='installmentpurchase', constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('card__isnull', True)), models.Q(('account__isnull', True), ('card__isnull', False)), _connector='OR'), name='installment_purchase_one_origin')),
        migrations.AddConstraint(model_name='installmentpurchase', constraint=models.UniqueConstraint(fields=('user', 'request_id'), name='unique_installment_request')),
        migrations.AddConstraint(model_name='transaction', constraint=models.CheckConstraint(condition=models.Q(models.Q(('installment_number__isnull', True), ('installment_purchase__isnull', True)), models.Q(('installment_number__isnull', False), ('installment_purchase__isnull', False), ('kind', 'expense'), ('subscription__isnull', True)), _connector='OR'), name='transaction_installment_fields')),
        migrations.AddConstraint(model_name='transaction', constraint=models.UniqueConstraint(fields=('installment_purchase', 'installment_number'), name='unique_purchase_installment_number')),
        migrations.AddConstraint(model_name='transaction', constraint=models.UniqueConstraint(fields=('installment_purchase', 'month'), name='unique_purchase_installment_month')),
    ]
